### ISSUE TITLE
请教个问题，关于8800指令

### ISSUE THREAD

**Issue by ccxdd** [cuteLittleDevil/go-jt808#2]
遇到的问题是主动拍照功能（8801），看文档里说0801需要用8800来应答，但0801一般都是有分包的，那么应答应该如何回复？
我现在情况是，只能收到0801的第一个包，回复后就没有后续的包了，用8800回复后，会再收到一条0001消息，结果是失败。请问可能是什么原因造成的？
发送的：7e8800000501330649643900030000000200ac7e
接收的：7e00010005013306496439003200038800019c7e

**Comment by ccxdd** [comment]
我按你说的调整了一下
接收0801：
```
7e0801231c01330649619901c1000a0001000000020000000100100000000c000301dac76c073dac4c0028000000c1241121162725ffd8ffe000104a46494600010100000100010000ffdb004300140e0f120f0d14121012171514181e32211e1c1c1e3d2c2e243249404c4b47404645505a736250556d5645466488656d777b8182814e608d978c7d0196737d02817cffdb0043011517171e1a1e3b21213b7c5346537c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7cffc00011080120016003012200021101031101ffc4001f0000010501010101010100000000000000000102030405060708090a0bffc400b5100002010303020403050504040000017d0101020300041105122131410613516107227114328191a1082342b1c11552d1f02433627282090a161718191a25262728292a3435363738393a434445464748494a535455565758595a636465666768696a737475767778797a838485868788898a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4b5b6b7b8b9bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae1e2e3e4e5e6e7e8e9eaf1f2f3f4f5f6f7f8f9faffc4001f0100030101010101010101010000000000000102030405060708090a0bffc400b51100020102040403040705040400010277000102031104052131061241510761711322328108144291a1b1c109233352f0156272d10a162434e125f11718191a262728292a35363738393a434445464748494a535455565758595a636465666768696a737475767778797a82838485868788898a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4b5b6b7b8b9bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae2e3e4e5e6e7e8e9eaf2f3f4f5f6f7f8f9faffda000c03010002110311003f00e755467a0a528a46428a14735756d07d018ccfbcee09bf18e31b82e33ebce68028ec1fdd14bb07f7455e96c42a42564cb3950d9180bb9430fd0fe949756be4bc6b1966f33200618390c57fa50053d8bfdd14796be83f2ab5776c6daee48036f287191de97d02cea1ae17ccc988646070dc807f9d0055f2d7d07d0254796be83f2a9da20b04720624b1604631617e
```
回复：
```
7e88000004013306496199000200000002097e
```
接收0001
```
7e0001000501330649619901c20002880001c97e
```

还是失败的，会不会有设备有关？等您的更新我再看看吧。

**Comment by cuteLittleDevil** [comment]
> 我按你说的调整了一下 接收0801：
> 
> ```
> 7e0801231c01330649619901c1000a0001000000020000000100100000000c000301dac76c073dac4c0028000000c1241121162725ffd8ffe000104a46494600010100000100010000ffdb004300140e0f120f0d14121012171514181e32211e1c1c1e3d2c2e243249404c4b47404645505a736250556d5645466488656d777b8182814e608d978c7d0196737d02817cffdb0043011517171e1a1e3b21213b7c5346537c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7cffc00011080120016003012200021101031101ffc4001f0000010501010101010100000000000000000102030405060708090a0bffc400b5100002010303020403050504040000017d0101020300041105122131410613516107227114328191a1082342b1c11552d1f02433627282090a161718191a25262728292a3435363738393a434445464748494a535455565758595a636465666768696a737475767778797a838485868788898a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4b5b6b7b8b9bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae1e2e3e4e5e6e7e8e9eaf1f2f3f4f5f6f7f8f9faffc4001f0100030101010101010101010000000000000102030405060708090a0bffc400b51100020102040403040705040400010277000102031104052131061241510761711322328108144291a1b1c109233352f0156272d10a162434e125f11718191a262728292a35363738393a434445464748494a535455565758595a636465666768696a737475767778797a82838485868788898a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4b5b6b7b8b9bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae2e3e4e5e6e7e8e9eaf2f3f4f5f6f7f8f9faffda000c03010002110311003f00e755467a0a528a46428a14735756d07d018ccfbcee09bf18e31b82e33ebce68028ec1fdd14bb07f7455e96c42a42564cb3950d9180bb9430fd0fe949756be4bc6b1966f33200618390c57fa50053d8bfdd14796be83f2ab5776c6daee48036f287191de97d02cea1ae17ccc988646070dc807f9d0055f2d7d07d0254796be83f2a9da20b04720624b1604631617e
> ```
> 
> 回复：
> 
> ```
> 7e88000004013306496199000200000002097e
> ```
> 
> 接收0001
> 
> ```
> 7e0001000501330649619901c20002880001c97e
> ```
> 
> 还是失败的，会不会有设备有关？等您的更新我再看看吧。


- 参考链接
https://github.com/cuteLittleDevil/go-jt808/tree/main/example/protocol/camera

0x0801是收完成后进行回复的
1. 关闭分包功能 使用自定义0x0801指令实现
2. 分包总数=分包序号的时候 说明完成了 进行回复

部分主要参考代码
``` go
	num := msg.Header.SubPackageNo
	sum := msg.Header.SubPackageSum
	t.schedule(num, sum)
	if num == sum && len(msg.Body) == int(msg.Header.Property.BodyDayaLen) { // 最后一个包
		t.subcontractComplete = true
	}
	if msg.ExtensionFields.SubcontractComplete { // 分包完成
		_ = t.T0x0801.Parse(msg.JTMessage)
		name := t.savePath()
		fmt.Println("包完成", name, time.Since(t.startTime), t.String())
		_ = os.WriteFile(name, t.T0x0801.MultimediaPackage, os.ModePerm)
	}

```

补包没搞用那个 目前例子是注释的
``` go
		fmt.Println(fmt.Sprintf("不连续的情况 之前进度[%d/%d] 现在进度[%d/%d]", t.num, t.sum, num, sum))
		// 不连续的情况 要补传 目前搞不懂用什么id（是流水号还是分包的序号呢）
		//seq := jtMsg.Header.SerialNumber // 流水号
		//seq := jtMsg.Header.SubPackageNo // 分包序号 以下是用分包序号的
		//for i := t.num + 1; i < num; i++ {
		//	t.repairPacketSeq = append(t.repairPacketSeq, i)
		//}

``` 

最后自定义回复
``` go
func (t *meT0801) ReplyBody(jtMsg *jt808.JTMessage) ([]byte, error) {
	_ = t.Parse(jtMsg)
	p8800 := model.P0x8800{
		MultimediaID: t.MultimediaID,
	}
	if len(t.repairPacketSeq) > 0 {
		p8800.AgainPackageCount = byte(len(t.repairPacketSeq))
		p8800.AgainPackageList = append(p8800.AgainPackageList, t.repairPacketSeq...)
		t.repairPacketSeq = t.repairPacketSeq[0:0]
	}
	return p8800.Encode(), nil
}

```

**Comment by ccxdd** [comment]
感谢您的帮助，问题已经解决。
